language: d

d:
  - dmd-2.071.0
  - dmd-2.070.0
  - dmd-2.069.0
  - dmd-2.068.2
  - dmd-2.067.1
  - ldc-0.16.1

matrix:
  allow_failures:
      - dmd-2.067.1
      - d: ldc-0.16.1

script:
  - dub test :base
  - dub test :compression
  - dub test :passhash
  - dub test :tls
  - dub test
